const { ethers } = require('ethers');
const crypto = require('crypto');

/**
 * Generates a SHA-256 hash of the crash telemetry and records it on-chain.
 * 
 * @param {string} incidentId - The MongoDB database _id string.
 * @param {string} rawLogs - The raw logs received in the crash report.
 * @param {string} diagnosis - The diagnosis text generated by the AI.
 * @param {string} proposedFix - The proposed fix text generated by the AI.
 * @returns {Promise<string>} The transaction hash (txHash) of the anchored record.
 */
async function hashAndLogIncident(incidentId, rawLogs, diagnosis, proposedFix) {
  // 1. Generate SHA-256 hash of the combined rawLogs, diagnosis, and proposedFix
  const combinedText = `${rawLogs || ''}${diagnosis || ''}${proposedFix || ''}`;
  const forensicHash = crypto
    .createHash('sha256')
    .update(combinedText)
    .digest('hex');

  console.log(`Generated forensic SHA-256 hash for incident ${incidentId}: ${forensicHash}`);

  // Load configuration from environment variables
  const rpcUrl = process.env.RPC_URL;
  const privateKey = process.env.WALLET_PRIVATE_KEY;
  const contractAddress = process.env.CONTRACT_ADDRESS;

  // Check if Web3 environment is configured
  if (!rpcUrl || !privateKey || !contractAddress) {
    console.warn('Web3 environment variables are incomplete. Falling back to mock transaction anchoring.');
    return simulateBlockchainAnchoring(incidentId, forensicHash);
  }

  try {
    // 2. Initialize JsonRpcProvider
    const provider = new ethers.JsonRpcProvider(rpcUrl);

    // 3. Initialize Wallet and connect to provider
    const wallet = new ethers.Wallet(privateKey, provider);

    // 4. Instantiate the smart contract
    // The contract ABI specifies the recordIncident(string,string) method
    const contractAbi = [
      'function recordIncident(string incidentId, string forensicHash) public returns (bool)'
    ];
    const contract = new ethers.Contract(contractAddress, contractAbi, wallet);

    console.log(`Initiating on-chain anchoring on contract: ${contractAddress}...`);

    // 5. Execute contract transaction recordIncident(incidentId, forensicHash)
    const tx = await contract.recordIncident(incidentId, forensicHash);
    console.log(`Transaction sent. Tx Hash: ${tx.hash}. Waiting for 1 block confirmation...`);

    // 6. Wait for 1 block confirmation
    const receipt = await tx.wait(1);
    const txHash = receipt.hash || tx.hash;
    console.log(`Transaction successfully anchored on-chain! Block Number: ${receipt.blockNumber}`);

    return txHash;
  } catch (error) {
    console.error(`Error anchoring incident on-chain for ID ${incidentId}:`, error.message);
    
    // Graceful error handling: Fallback to simulated anchoring to prevent crash telemetry loss
    return simulateBlockchainAnchoring(incidentId, forensicHash);
  }
}

/**
 * Simulation helper for local development or when Web3 RPC fails.
 */
function simulateBlockchainAnchoring(incidentId, forensicHash) {
  const simulatedHash = '0x' + crypto
    .createHash('sha256')
    .update(incidentId + forensicHash + Date.now().toString())
    .digest('hex');
  
  console.log(`[SIMULATED] Telemetry successfully anchored. Mock Tx Hash: ${simulatedHash}`);
  return simulatedHash;
}

/**
 * Queries the blockchain contract to retrieve the anchored SHA-256 hash for a given incident ID.
 * 
 * @param {string} incidentId - The MongoDB database _id string.
 * @returns {Promise<string|null>} The anchored forensic hash or null if not found/error.
 */
async function getIncidentHashOnChain(incidentId) {
  const rpcUrl = process.env.RPC_URL;
  const contractAddress = process.env.CONTRACT_ADDRESS;

  if (!rpcUrl || !contractAddress) {
    console.warn('Web3 environment is incomplete. Cannot query on-chain hash.');
    return null;
  }

  try {
    const provider = new ethers.JsonRpcProvider(rpcUrl);
    const contractAbi = [
      'function getIncidentHash(string incidentId) public view returns (string)'
    ];
    const contract = new ethers.Contract(contractAddress, contractAbi, provider);

    const hash = await contract.getIncidentHash(incidentId);
    return hash || null;
  } catch (error) {
    console.error(`Error querying blockchain for incident ID ${incidentId}:`, error.message);
    return null;
  }
}

module.exports = {
  hashAndLogIncident,
  getIncidentHashOnChain
};
